"""Plot learning curves for Montezuma's Revenge."""

from montezuma import Task

from rfd.agent import Agent
from rfd.procedures import plot

DEMO_FILE = "saved/demo.pkl"  # Generated by demonstrate.py
PLOT_FILE = "saved/plot.txt"  # Created by this script

CURVES = 10  # Number of agents to train
ATTEMPTS = 100000  # How long to train each agent
WINDOW = 10000  # Attempts averaged into each point
FREQUENCY = 1000  # Attempts between points

agent_generator = lambda: Agent(extend_map=False)  # Demo should provide a complete path
plot(agent_generator, lambda: Task(), DEMO_FILE, PLOT_FILE, CURVES, ATTEMPTS, WINDOW, FREQUENCY)
