"""Train and save an agent for Montezuma's Revenge with extended actions."""

from montezuma import Task

from rfd.agent import Agent
from rfd.procedures import train

DEMO_FILE = "saved/demo.pkl"  # Generated by demonstrate.py
AGENT_FILE = "saved/agent.pkl"  # Created by this script

ATTEMPTS = 2000  # How long to train the agent
WINDOW = 200  # Attempts averaged into each score report
FREQUENCY = 20  # Attempts between score reports

agent = Agent(extend_map=False)  # Demo should provide a complete path
train(agent, lambda: Task(), DEMO_FILE, AGENT_FILE, ATTEMPTS, WINDOW, FREQUENCY)
