"""Plot learning curves for Ms. Pacman."""

from pacman import Task

from rfd.agent import Agent
from rfd.procedures import plot

DEMO_FILE = "saved/demo.pkl"  # Generated by demonstrate.py
PLOT_FILE = "saved/plot.txt"  # Created by this script

CURVES = 10  # Number of agents to train
ATTEMPTS = 1000  # How long to train each agent
WINDOW = 100  # Attempts averaged into each point
FREQUENCY = 10  # Attempts between points

agent_generator = lambda: Agent(extend_theory=False)  # Demo should provide complete causality
plot(agent_generator, lambda: Task(), DEMO_FILE, PLOT_FILE, CURVES, ATTEMPTS, WINDOW, FREQUENCY)
