"""Train and save an agent for Ms. Pacman."""

from pacman import Task

from rfd.agent import Agent
from rfd.procedures import train

DEMO_FILE = "saved/demo.pkl"  # Generated by demonstrate.py
AGENT_FILE = "saved/agent.pkl"  # Created by this script

ATTEMPTS = 1000  # How long to train the agent
WINDOW = 100  # Attempts averaged into each score report
FREQUENCY = 10  # Attempts between score reports

agent = Agent(extend_theory=False)  # Demo should provide complete causality
train(agent, lambda: Task(), DEMO_FILE, AGENT_FILE, ATTEMPTS, WINDOW, FREQUENCY)
