"""Plot learning curves for Taxi."""

from taxi import Task

from rfd.agent import Agent
from rfd.procedures import plot

DEMO_FILE = "saved/demo.pkl"  # Generated by demonstrate.py
PLOT_FILE = "saved/plot.txt"  # Created by this script

CURVES = 10  # Number of agents to train
ATTEMPTS = 300  # How long to train each agent
WINDOW = 30  # Attempts averaged into each point
FREQUENCY = 3  # Attempts between points

plot(lambda: Agent(), lambda: Task(), DEMO_FILE, PLOT_FILE, CURVES, ATTEMPTS, WINDOW, FREQUENCY)
