"""Train and save an agent for Taxi."""

from taxi import Task

from rfd.agent import Agent
from rfd.procedures import train

DEMO_FILE = "saved/demo.pkl"  # Generated by demonstrate.py
AGENT_FILE = "saved/agent.pkl"  # Created by this script

ATTEMPTS = 300  # How long to train the agent
WINDOW = 30  # Attempts averaged into each score report
FREQUENCY = 3  # Attempts between score reports

train(Agent(), lambda: Task(), DEMO_FILE, AGENT_FILE, ATTEMPTS, WINDOW, FREQUENCY)
